FROM rnsloan/redis
MAINTAINER R Sloan "rnsloan1@gmail.com"
ENV REFRESHED_AT 2015-03-21

ENTRYPOINT [ "redis-server", "--logfile /var/log/redis/redis-server.log" ]

# docker run -d -h redis_primary --name redis_primary rnsloan/redis_primary
